### ISSUE TITLE
Remove password field from register response

### ISSUE THREAD

**Issue by sebas-tcotd** [hbars3/medcord-backend#16]
The response from the endpoint `https://sgdapidev.medcord.cf/users/register` is giving the password property as part of it.

Even though it's encrypted, it's recommended not to send it for security reasons.

I share evidence:
![image](https://user-images.githubusercontent.com/33919190/202867910-2169d8f1-ca0b-4672-8f5a-c289d3c1019d.png)

**Comment by Maurck** [comment]
Thank you for reporting this security breach, I will close this issue since it's already fixed and waiting for deployment.

- Mauricio Linares - Backend team
